### PR TITLE
Convert over to persistence

### PR DESCRIPTION
**Pull request by oldfartdeveloper**
Now persistence works, thanks to Drew.

This pull request fixes the code and tests to handle persistence.

CAUTION!  Running tests will probably destroy your data in your development Rails database.  We'll fix this soon.

### CODE REVIEW

**Comment by andrewmp1** [comment]
Scott,

I think there are some merge conflicts here.  You need to merge develop into data before this pull request can be merged cleanly.

**Comment by oldfartdeveloper** [comment]
Rats.  Sorry about that.

On Tue, Apr 17, 2012 at 9:08 AM, Drew <
reply@reply.github.com

> wrote:
> 
> Scott,
> 
> I think there are some merge conflicts here.  You need to merge develop
> into data before this pull request can be merged cleanly.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/OC-Emberjs/yourjargon/pull/45#issuecomment-5179036

## 

Scott Smith

http://twitter.com/_ofd (OldFartDeveloper)

**Comment by andrewmp1** [comment]
No worries.  I'm going to do merge with develop now and then you can just
update the pull request against the new commits

On Tue, Apr 17, 2012 at 11:49 AM, Scott Smith <
reply@reply.github.com

**Comment by oldfartdeveloper** [comment]
Sounds good. Sorry to get back to you so late, today's been nuts.

See you tonight.

**Pull request closed without merging**
